fresh_start : true
data:
  lengths: &seq_lens
    past_len: 16
   # horizon: 1 this has to be 1 due to the pqc architechture.
  ticker_symols:
    - AAPL
    - BTC-USD
    - IAG.L
  data_path: null
  preprocess: true
  start: null # yyyy-mm-dd or null for all past
  end: 2021-06-07   # yyyy-mm-dd or null for up to present
  scale_range: # Scale range for the BiLSTM (PQC is always scalled 0 to 1)
    - 0.2
    - 0.8
  kwargs:
    test_frac: 0.25 # fraction of data to reserve for testing
    val_frac: 0.2 # fraction of the training set to use for validation. Set to 0 to forgo validation
    colname: Perc_Change # or use "Close"
models:
  common:
    init: &comminit
      <<: *seq_lens
      metrics:
        - sesd
        - mr
        - sdr
      save_dir: ./results_reproduction # then do <model>/<ticker>/<model> + weights.pt & results
    train: &commtrain
      epochs: 300
      load_pretrained: false # can overwrite in model sections
      train: true            # ditto
      test: true
  BiLSTM:
    init:
      <<: *comminit
      add_metrics: 
        - mse
      summary: true
      pt_filename: best.weights.h5
    train:
      <<: *commtrain
      weight_save_filename: trained.weights.h5
  PQC:
    init:
      <<: *comminit
      add_metrics:
        - qmse
      blocks: 2
      pt_filename: best.params
      random_init_weights: true
    train:
      <<: *commtrain
      weight_save_filename: trained.params
      kwargs:
        verbose: true
        batch_size: 30
        patience: 25
        shuffle: true
        initial_epoch: 0
        validation_freq: 1
