data:
  lengths: &seq_lens
    past_len: 16
   # horizon: 1 this has to be 1 due to the pqc architechture.
  ticker_symols:
    - AAPL
  # data_path: null
  preprocess: true
  start: null # yyyy-mm-dd or null for all past
  end: null   # yyyy-mm-dd or null for up to present
  scale_range: # Scale range for the BiLSTM (PQC is always scalled 0 to 1)
    - 0.2
    - 0.8
  kwargs:
    test_frac: 0.25 # fraction of data to reserve for testing
    val_frac: 0.2 # fraction of the training set to use for validation. Set to 0 to forgo validation
    colname: "Perc_Change" # or use "Colse"
  # preprocess: true
# script:
#   test: true
#   train: true
models:
  common:
    init: &comminit
      <<: *seq_lens
      metrics:
        - sesd
        - mr
        - sdr
    train: &commtrain
      epochs: 300
      load_pretrained: False # can overwrite in model sections
      save_dir: ./results # then do <model>/<ticker>/weights.pt & results
  BiLSTM:
    init:
      <<: *comminit
      add_metrics: 
        - mse
      summary: true
    train:
      <<: *commtrain
      train: true
    test: true
  PQC:
    init:
      <<: *comminit
      add_metrics:
        - qmse
      blocks: 2
    train:
      <<: *commtrain
      train: true
      kwargs:
        verbose: false
        batch_size: 30
        patience: 25
        shuffle: true,
        initial_epoch: 0,
        validation_freq: 1,
    test: true